spring.application.name=ms.resenas
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/ms_resenas_db?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

servicios.compras.biblioteca.url=http://localhost:8083/api/biblioteca
servicios.timeout.segundos=5

logging.level.cl.duoc.tienda.ms.resenas=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} %-5l\
  evel [%logger{0}] - %msg%n