spring.application.name=ms.promociones
server.port=8086

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ms_promociones_db?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#URLs de microservicios conectados
servicios.catalogo.juegos.url=http://localhost:8082/api/juegos

#Timeouts
servicios.timeout.segundos=5

#Log
logging.level.cl.duoc.tienda.ms.promociones=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%logger{0}] - %msg%n

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html